---
- name: add service ignore error script
  become: True
  template:
    src: service-ignore-error.j2
    dest: "/etc/rsyslog-ignore.d/{{ hive_safe_target }}.conf"
    mode: 0755
  when: not (hive_destroy | default(False))
  loop: "{{ hive_safe_services | map('extract', hostvars) | selectattr('hive_ignore_error', 'defined') | map(attribute='inventory_hostname') | list }}"
  loop_control:
    loop_var: hive_safe_target
- name: remove service ignore error script
  become: True
  file:
    path: "/etc/rsyslog-ignore.d/{{ hive_safe_target }}.conf"
    state: absent
  when: hive_destroy | default(False)
  loop: "{{ hive_safe_services | map('extract', hostvars) | selectattr('hive_ignore_error', 'defined') | map(attribute='inventory_hostname') | list }}"
  loop_control:
    loop_var: hive_safe_target
  notify: update rsyslog config

